cok
Signed-off-by: najahiiii <tlogitechnjhi@gmail.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,33 +1,63 @@
 #!bin/bash
 IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
-git clone https://github.com/najahiiii/aarch64-linux-gnu.git -b gcc5-20190314 gcc
-curl -F chat_id="$chat_id" -F sticker="CAADBQAD7wADQxCzIs\_rqaRTwvagAg" https://api.telegram.org/bot$token/sendSticker
-curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>ChipsKernel CAF</b> new build is up"'!'"%0AStarted on <code>$(hostname)</code>%0AFor device <b>ROLEX</b> (Redmi 4A)%0Abranch <code>"$(git rev-parse --abbrev-ref HEAD)"</code>%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0ACompiler <code>$(${PWD}/gcc/bin/aarch64-linux-gnu-gcc --version | head -n 1)</code>%0AStarted on <code>$(date)</code>%0A<b>Build Status:</b> #untested%0A<b>Semaphore CI Build Info</b> - <a href='https://semaphoreci.com/najahiiii/moaikernal'>Status</a>"
+git clone https://github.com/najahiiii/aarch64-linux-gnu.git -b linaro8-20190216 gcc
+GCC="$(pwd)/gcc/bin/aarch64-linux-gnu-"
+CLANG_TRIPLE=aarch64-linux-gnu-
+CLANG_LD=aarch64-linux-gnu-ld.gold
+curl -s -F chat_id=$chat_id -F sticker="CAADBQAD7wADQxCzIs_rqaRTwvagAg" https://api.telegram.org/bot$token/sendSticker
+curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>ChipsKernel CAF</b> new build is up"'!'"%0AStarted on <code>$(hostname)</code>%0AFor device <b>ROLEX</b> (Redmi 4A)%0Abranch <code>$(git rev-parse --abbrev-ref HEAD)</code>%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0ACompiler <code>$(${GCC}gcc --version | head -n 1)</code>%0AClang <code>$(${CT} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</code>%0AStarted on <code>$(date)</code>%0A<b>Build Status:</b> #untested%0A<b>Semaphore CI Build Info</b> - <a href='https://semaphoreci.com/najahiiii/moaikernal'>Status</a>"
 tanggal=$(date +'%H%M-%d%m%y')
 START=$(date +"%s")
 export ARCH=arm64
 export KBUILD_BUILD_USER=Najahi
-export KBUILD_BUILD_HOST=SemaphoreCI
+export CLANG_TRIPLE
+export CLANG_LD
 export USE_CCACHE=1
 export CACHE_DIR=~/.ccache
+# Function to upload to ix.io
+function sprunge() {
+    cat build.log | curl -F 'sprunge=<-' http://sprunge.us > link
+    HASIL="$(cat link)"
+}
+# Function to upload to pastebin.com
+function pastebin() {
+    title="build.log"
+    expiration="N"
+    token="ddfc4ce9d8ad271c0c02f4c6ba708b8e"
+    input="$(cat build.log)"
+    user_key="9a7a9136e6cc54ef0d82eb936d73be89"
+    query="api_option=paste&api_dev_key=${token}&api_user_key=${user_key}&api_paste_code=${input}&api_paste_private=1&api_paste_name=${title}&api_paste_expire_date=${expiration}"
+    curl -s -X POST https://pastebin.com/api/api_post.php -d "${query}" > link
+    HASIL="$(cat link)"
+}
+# Function to upload to del.dog
+function deldog() {
+    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
+        echo "ERROR: failed to post document" >&2
+        exit 1
+    }
+    KEY=$(jq -r .key <<< "${RESULT}")
+    echo "https://del.dog/raw/${KEY}"
+}
 # Fin Error
 function finerr() {
-        curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=markdown&text=Build throw an error(s)"
+        sprunge
+        curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=html&text=Build throw an error(s) | <b>Build logs</b> <a href='${HASIL}'>here</a>"
         exit 1
 }
-make -C $(pwd) O=out rolex_defconfig
-make -C $(pwd) CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-linux-gnu- O=out -j6 -l4
+make -s -C $(pwd) O=out rolex_defconfig
+make -s -C $(pwd) CROSS_COMPILE=${GCC} O=out -j6 -l8 2>&1| tee build.log
 if ! [ -a $IMAGE ]; then
-	echo -e "Error Cok"
 	finerr
 	exit 1
 fi
 cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage
+sprunge
 cd AnyKernel
-zip -r9 ChipsKernel-Pie-GCC5-${tanggal}.zip *
+zip -r9 ChipsKernel-Pie-${tanggal}.zip *
 END=$(date +"%s")
 DIFF=$(($END - $START))
-curl -F chat_id="$chat_id" -F document=@"ChipsKernel-Pie-GCC5-${tanggal}.zip" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds. | #unified" https://api.telegram.org/bot$token/sendDocument
+curl -F chat_id="$chat_id" -F document=@"ChipsKernel-Pie-${tanggal}.zip" -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). | <b>Build logs</b> <a href='${HASIL}'>here</a> | #unified" https://api.telegram.org/bot$token/sendDocument
 cd ..
 rm -rf out
 rm -rf AnyKernel/zImage
