add deldog
Signed-off-by: najahiiii <tlogitechnjhi@gmail.com>

diff --git a/clang b/clang
--- a/clang
+++ b/clang
@@ -10,13 +10,22 @@ export ARCH=arm64
 export KBUILD_BUILD_USER=Najahi
 export USE_CCACHE=1
 export CACHE_DIR=~/.ccache
+# Function to upload to del.dog
+function deldog() {
+    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
+        echo "ERROR: failed to post document" >&2
+        exit 1
+    }
+    KEY=$(jq -r .key <<< "${RESULT}")
+    echo "https://del.dog/raw/${KEY}"
+}
 # Fin Error
 function finerr() {
         curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=markdown&text=Build throw an error(s)"
         exit 1
 }
 make -s -C $(pwd) O=out rolex_defconfig
-make -C $(pwd) CC=$(pwd)/clang/bin/clang CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-chips-linux-android- O=out -j6 -l4
+nohup make -C $(pwd) CC=$(pwd)/clang/bin/clang CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-chips-linux-android- O=out -j6 -l4 >> build.log
 if ! [ -a $IMAGE ]; then
 	echo -e "Error Cok"
 	finerr
@@ -32,3 +41,4 @@ cd ..
 rm -rf out
 rm -rf AnyKernel/zImage
 rm -rf AnyKernel/ChipsKernel*.zip
+deldog build.log
